---
title: "Challenge 2"
author: "Amber"
date: "2024-03-05"
output: html_document
---

## Step One
Load in the dataset and necessary packages
```
{r}
install.packages ("tidyverse")
library (tidyverse)

install.packages ("mosaic")
library (mosaic)
```

And the data

```
{r}
f <- "https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/zombies.csv"
z <- read_csv (f, col_names=TRUE)
```

## Step Two 
Calculate the population mean and standard deviation for each quantitive random variable in the dataset (height, weight, age, number of zombies killed, and years of education)

To begin, I created a function to calculate the population standard deviation for ease of calculation:
```
{r}
sd_pop=function(x){
  sd(x)*sqrt((length(x)-1)/length(x))
  }
```

And then calculated each:
```
{r}
mean_height <- mean(z$height)
sd_height <- sd(z$height)
mean_weight <- mean(z$weight)
sd_weight <- sd(z$weight)
mean_age <- mean(z$age)
sd_age <- sd(z$age)
mean_kills <- mean(z$zombies_killed)
sd_kills <- sd(z$zombies_killed)
mean_edu <- mean(z$years_of_education)
sd_edu <- sd(z$years_of_education)
```

## Step three
Use {ggplot} to make boxplots of each of these by gender. I struggled a lot with this step and still could not figure out how to expand the values to unsquish the variables with smaller values. To begin, I separated the dataset into male and female, then shifted my data into long format to allow for the use of face_grid.  

```
{r}
#separate data into two datasets for sex
z_female <- filter (z, gender=="Female")
z_male <- filter (z, gender=="Male")

# separate out the variables we want to use in facet_grid
fem_long <- pivot_longer(z_female, c("height", "weight", "age", "zombies_killed", "years_of_education"), names_to = "Variable",
    values_to = "Value")
m_long <- pivot_longer(z_male, c("height", "weight", "age", "zombies_killed", "years_of_education"), names_to = "Variable",
    values_to = "Value")

p <- ggplot(data = fem_long, aes(x = factor(0), y = Value)) + geom_boxplot(na.rm = TRUE,
    outlier.shape = NA) + theme(axis.title.x = element_blank(), axis.text.x = element_blank(),
    axis.ticks.x = element_blank()) + geom_dotplot(binaxis = "y", stackdir = "center",
    stackratio = 0.2, alpha = 0.3, dotsize = 0.5, color = NA, fill = "red", na.rm = TRUE) +
    facet_grid(. ~ Variable) + geom_rug(sides = "l")
#to view plot
p

q <- ggplot(data = m_long, aes(x = factor(0), y = Value)) + geom_boxplot(na.rm = TRUE,
    outlier.shape = NA) + theme(axis.title.x = element_blank(), axis.text.x = element_blank(),
    axis.ticks.x = element_blank()) + geom_dotplot(binaxis = "y", stackdir = "center",
    stackratio = 0.2, alpha = 0.3, dotsize = 0.5, color = NA, fill = "blue", na.rm = TRUE) +
    facet_grid(. ~ Variable) + geom_rug(sides = "l")
# to view plot
q
```

## Step Four
Use {ggplot} to make scatterplots of height and weight in realtion to age (age as x variable), using different colored points for males versus females.

```
{r}
hplot <- ggplot (data = z, aes(x=age, y=height, color = factor(gender))) + geom_point(na.rm=TRUE)
wplot <- ggplot (data= z, aes(x=age, y=weight, color = factor(gender))) + geom_point(na.rm=TRUE)
```

In both height and weight, the males had generally higher scores. With height, the difference in sexes became more pronounced after around age 20. With weight, the differences became less pronounced after around age 20, but the change in difference was less pronounced overall. 

## Step Five
Using histograms and Q-Q plots, check whether each of the quantitive variables seems to be drawn from normal distribution.Unfortunately, like in class, the plotDist function did not actively overlap the histogram and I was unable to get an alternative function to work, but they can be visually compared.

Checking:
```
{r}
# age
hist (z$age)
plotDist ("norm", add=TRUE)
qqnorm(z$age, pch = 1, frame = FALSE)
qqline(z$age, col = "steelblue", lwd = 2)

# height
hist (z$height)
plotDist ("norm", add=TRUE)
qqnorm(z$height, pch = 1, frame = FALSE)
qqline(z$height, col = "steelblue", lwd = 2)

# weight
hist (z$weight)
plotDist ("norm", add=TRUE)
qqnorm(z$weight, pch = 1, frame = FALSE)
qqline(z$weight, col = "steelblue", lwd = 2)

# zombie kills
hist (z$zombies_killed)
plotDist ("norm", add=TRUE)
qqnorm(z$zombies_killed, pch = 1, frame = FALSE)
qqline(z$zombies_killed, col = "steelblue", lwd = 2)

# years of education
hist (z$years_of_education)
plotDist ("norm", add=TRUE)
qqnorm(z$years_of_education, pch = 1, frame = FALSE)
qqline(z$years_of_education, col = "steelblue", lwd = 2)
```

Weight, height, and age are drawn from normal distribution.
Zombies killed and years of education are not. 

## Step 6

I've started by sampling a subset of 50 zombie apocalypse survivors without replacement and calculating the mean and standard deviation for each variable, as well as the standard error. 
```
{r}
results_sampled <- z %>% 
  slice_sample (n=50, replace = FALSE) %>%
  summarize (n = n(),
    m_age = mean(age),
    sd_age = sd(age),
    se_age = sd_age/sqrt(n),
    m_height = mean(height),
    sd_height = sd(height),
    se_height = sd_height/sqrt(n),
    m_weight = mean(weight),
    sd_weight = sd(weight),
    se_weight = sd_weight/sqrt(n),
    m_kills = mean(zombies_killed),
    sd_kills = sd(zombies_killed),
    se_kills = sd_kills/sqrt(n),
    m_edu = mean(years_of_education),
    sd_edu = sd(years_of_education),
    se_edu = sd_edu/sqrt(n))
```

Now I will use these stats to construct a theoretical 95% confidence interval for each mean. Again, there is likely a neater way to do it, but I could not quite get a function to work quite right.
```
{r}
alpha <- 1 - 95/100
(ci_age <- results_sampled$m_age + c(-1, 1) * qnorm(1 - alpha/2) * results_sampled$se_age)
(ci_weight <- results_sampled$m_weight + c(-1, 1) * qnorm(1 - alpha/2) * results_sampled$se_weight)
(ci_height <- results_sampled$m_height + c(-1, 1) * qnorm(1 - alpha/2) * results_sampled$se_height)
(ci_kills <- results_sampled$m_kills + c(-1, 1) * qnorm(1 - alpha/2) * results_sampled$se_kills)
(ci_edu <- results_sampled$m_edu + c(-1, 1) * qnorm(1 - alpha/2) * results_sampled$se_edu)
```

## Step 7
Then draw another 199 random samples of 50 zombie apocalypse survivors and calculate the mean for each of these. I tried a few ways of adding the materials of results_sampled to his, and couldn't quite get it to work, so I just did 200 random samples instead:
```
{r}
n_reps <- 200
reps <- vector(length=200)
s <- z

for (i in 1:n_reps){
sampling_distribution <- s %>% 
  slice_sample (n=50, replace = FALSE)
  }
  
sampled_stats <- sampling_distribution %>%  
  summarize (n = n(),
    sam_mean_age = mean(age),
    sam_sd_age = sd(age),
    sam_mean_height = mean(height),
    sam_sd_height = sd(height),
    sam_mean_weight = mean(weight),
    sam_sd_weight = sd(weight),
    sam_mean_kills = mean(zombies_killed),
    sam_sd_kills = sd(zombies_killed),
    sam_mean_edu = mean(years_of_education),
    sam_sd_edu = sd(years_of_education))
  
  view(sampled_stats)
```

The standard deviations of the sampling distribution are within the standard error of the standard deviations of the results from the original sample, seen in results_sampled. 

## Step 8
Plot the sampling distributions for each variable mean. 

```
ggplot(sampling_distribution, aes(x = age)) + geom_histogram(binwidth=2, fill= "red") 
ggplot(sampling_distribution, aes(x = height)) + geom_histogram(binwidth=5, fill= "green") 
ggplot(sampling_distribution, aes(x = weight)) + geom_histogram(binwidth=5, fill= "blue") 
ggplot(sampling_distribution, aes(x = zombies_killed)) + geom_histogram(binwidth=2, fill= "purple") 
ggplot(sampling_distribution, aes(x = years_of_education)) + geom_histogram(binwidth=2, fill= "orange") 
```

## Step 9
Construct a 95% confidence interval for each mean from the sampling distribution of sample means
```
{r}
(ci_age_samp <- quantile(sampling_distribution$age, c(0.025,0.975)))
(ci_height_samp <- quantile(sampling_distribution$height, c(0.025,0.975)))
(ci_weight_samp <- quantile(sampling_distribution$weight, c(0.025,0.975)))
(ci_kills_samp <- quantile(sampling_distribution$zombies_killed, c(0.025,0.975)))
(ci_edu_samp <- quantile(sampling_distribution$years_of_education, c(0.025,0.975)))
```
How do the sampling_distribution CIs compare to the CI based on one sample?

The CIs from the sampling_distribution set have a wider range; the lower number is lower and the higher number is higher. 

## Step 10
```
{r}
# age
n_boot <- 10000
boot_age <- vector(length = n_boot)  
n <- length(z)

for (i in 1:n_boot) {
    boot_age [[i]] <- mean(sample(z$age, n, replace = TRUE))
}
(ci_boot_age <- quantile(boot_age, c(0.025,0.975)))

# height
boot_height <- vector(length = n_boot)  

for (i in 1:n_boot) {
    boot_height [[i]] <- mean(sample(z$height, n, replace = TRUE))
}
(ci_boot_height <- quantile(boot_height, c(0.025,0.975)))

# weight
boot_weight <- vector(length = n_boot)  

for (i in 1:n_boot) {
    boot_weight [[i]] <- mean(sample(z$weight, n, replace = TRUE))
}
(ci_boot_weight <- quantile(boot_weight, c(0.025,0.975)))

# zombies killed
boot_kills <- vector(length = n_boot)  

for (i in 1:n_boot) {
    boot_kills [[i]] <- mean(sample(z$zombies_killed, n, replace = TRUE))
}
(ci_boot_kills <- quantile(boot_kills, c(0.025,0.975)))

# years of education
boot_edu <- vector(length = n_boot)  

for (i in 1:n_boot) {
    boot_edu [[i]] <- mean(sample(z$years_of_education, n, replace = TRUE))
}
(ci_boot_edu <- quantile(boot_edu, c(0.025,0.975)))
```
